[senhas]
login_um = "senhaSecreta01"
login_dois = "senhaSecreta02"
login_tres = "senhaSecreta03"
login_quatro = "senhaSecreta04"
BC_Marcela = "M@rcela40"
login_seis = "senhaSecreta06"

[arquivos]
# Relaciona cada um dos 6 logins ao seu arquivo .py exclusivo
login_um = "paginas/app_clinica1.py"
login_dois = "paginas/app_clinica2.py"
login_tres = "paginas/app_clinica3.py"
login_quatro = "paginas/app_clinica4.py"
BC_Marcela = "paginas/app_bc_marcela.py"
login_seis = "paginas/app_clinica6.py"