[senhas]

BC_Marcela = "M@rcela40"
Thacira = "Th@cira41"
Bruno_Cosme = "C0sme42"
Bruno_Campos = "C@mpos43"
Pablo_Auad = "P@blo44"
Olivia_Queiroga = "Olivi@45" 

[arquivos]
# Relaciona cada um dos 6 logins ao seu arquivo .py exclusivo
BC_Marcela = "paginas/app_bc_marcela.py"
Thacira = "paginas/app_thacira.py"
Bruno_Cosme = "paginas/app_cosme.py"
Bruno_Campos = "paginas/app_campos.py"
Pablo_Auad = "paginas/app_pablo.py"
Olivia_Queiroga = "paginas/app_olivia.py"